save release status

diff --git a/.github/workflows/run-release-prd.yml b/.github/workflows/run-release-prd.yml
--- a/.github/workflows/run-release-prd.yml
+++ b/.github/workflows/run-release-prd.yml
@@ -14,17 +14,32 @@ concurrency:
   cancel-in-progress: false
 
 jobs:
-  validate-stg-release:
+  validate-release:
     runs-on: ubuntu-latest
     steps:
-      - name: Verfify CI status of the stg release
+      - name: Validate semver
+        run: |
+          if [[ ! ${{ inputs.semver }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid semver: ${{ inputs.semver }}"
+            exit 1
+          fi
+      
+      - name: Ensure tag exists
+        run: |
+          release=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ inputs.semver }})
+          if [[ $release_code != "200" ]]; then
+            echo "Tag ${{ inputs.semver }} does not exist."
+            exit 1
+          fi
+
+      - name: Verfify CI status of the stg release tag
         run: |
           status=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/commits/${{ inputs.semver }}/status)
           echo "status_code=$status" >> GITHUB_OUTPUT
 
   cd:
     uses: ./.github/workflows/_sls_deploy.yml
-    needs: validate-stg-release
+    needs: validate-release
     with:
       ref: ${{ github.sha }}
       release_semver: ${{ inputs.semver }}
